#!/bin/bash

# /path/to/ampl directory
AMPL_PATH='/Users/alberto/Documents/Universita/RicercaOperativa/ampl.macos64'
OPL_PATH="$PWD/opl"
SCENARIO="$OPL_PATH/scenario-$1.run"

echo $OPL_PATH
cd $AMPL_PATH
$AMPL_PATH/ampl -g $SCENARIO

